# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 16:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adi', '0033_guardia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('nombre', models.CharField(max_length=25, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=25, verbose_name='Apellido')),
                ('dni', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='DNI')),
                ('email', models.CharField(max_length=50, null=True, verbose_name='Direcci\xf3n e-mail')),
                ('num_cel', models.CharField(max_length=14, null=True, verbose_name='N\xfamero de celular')),
                ('codigo_como_firma', models.CharField(default='0WJFK', max_length=5, unique=True, verbose_name='Firma')),
            ],
            options={
                'verbose_name': 'Tutor',
                'verbose_name_plural': 'Tutores',
            },
        ),
        migrations.AlterModelOptions(
            name='alumno',
            options={'verbose_name': 'Alumno', 'verbose_name_plural': 'Alumnos'},
        ),
        migrations.AlterModelOptions(
            name='curso',
            options={'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AlterModelOptions(
            name='formulario',
            options={'verbose_name': 'Formulario', 'verbose_name_plural': 'Formularios'},
        ),
        migrations.AlterModelOptions(
            name='guardia',
            options={'verbose_name': 'Guardia', 'verbose_name_plural': 'Guardias'},
        ),
        migrations.AlterModelOptions(
            name='preceptor',
            options={'verbose_name': 'Preceptor', 'verbose_name_plural': 'Preceptores'},
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='faltas',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='id',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='padre',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='year',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='preceptor',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='guardia',
            name='id',
        ),
        migrations.RemoveField(
            model_name='preceptor',
            name='nombre_usuario',
        ),
        migrations.AddField(
            model_name='alumno',
            name='amonestaciones',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Amonestaciones'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='direccion',
            field=models.CharField(max_length=100, null=True, verbose_name='Calle'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='fecha_nacimiento',
            field=models.DateField(null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='foto',
            field=models.ImageField(max_length=60, null=True, upload_to='adi/static/media/img/fotos_alumnos/', verbose_name='Foto'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='inasistencias_injustificadas',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=2, verbose_name='Inasistencias Injustificadas'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='inasistencias_justificadas',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=2, verbose_name='Inasistencias Justificadas'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='legajo',
            field=models.PositiveSmallIntegerField(null=True, unique=True, verbose_name='Legajo'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='observaciones',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Observaciones'),
        ),
        migrations.AddField(
            model_name='curso',
            name='anuario',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], default=12, verbose_name='A\xf1o'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curso',
            name='id',
            field=models.AutoField(auto_created=True, default=12, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formulario',
            name='guardia',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='formularios', to='adi.Guardia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formulario',
            name='motivo',
            field=models.CharField(max_length=254, null=True, verbose_name='Motivo'),
        ),
        migrations.AddField(
            model_name='formulario',
            name='tipo_formulario',
            field=models.CharField(choices=[('F1', 'Formulario 1'), ('F2', 'Formulario 2'), ('F3', 'Formulario 3')], default=12, max_length=2, verbose_name='Tipo de formulario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guardia',
            name='num_cel',
            field=models.CharField(max_length=14, null=True, verbose_name='N\xfamero de celular'),
        ),
        migrations.AddField(
            model_name='preceptor',
            name='email',
            field=models.EmailField(max_length=100, null=True, verbose_name='Direcci\xf3n e-mail'),
        ),
        migrations.AddField(
            model_name='preceptor',
            name='num_cel',
            field=models.CharField(max_length=14, null=True, verbose_name='N\xfamero de celular'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='apellido',
            field=models.CharField(max_length=25, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumnos', to='adi.Curso'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='dni',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='estado',
            field=models.CharField(choices=[('PR', 'Presente'), ('AU', 'Ausente'), ('RE', 'Retirado'), ('TA', 'Lleg\xf3 tarde'), ('ND', 'Indefinido')], default=('ND', 'Indefinido'), max_length=2, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='nombre',
            field=models.CharField(max_length=25, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='division',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1, verbose_name='Divisi\xf3n'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='preceptor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='adi.Preceptor'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='alumno',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alumno', to='adi.Alumno'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='estado',
            field=models.CharField(choices=[(True, 'Entregado'), (False, 'No entregado')], default=(False, 'No entregado'), max_length=2, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='guardia',
            name='apellido',
            field=models.CharField(max_length=25, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='guardia',
            name='dni',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='guardia',
            name='nombre',
            field=models.CharField(max_length=25, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='preceptor',
            name='apellido',
            field=models.CharField(max_length=25, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='preceptor',
            name='dni',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='preceptor',
            name='nombre',
            field=models.CharField(max_length=25, verbose_name='Nombre'),
        ),
        migrations.DeleteModel(
            name='Padre_Tutor',
        ),
        migrations.AddField(
            model_name='alumno',
            name='tutor',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='hijos', to='adi.Tutor'),
            preserve_default=False,
        ),
    ]
