# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 21:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('adi', '0036_auto_20171116_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='preceptor',
            name='grupo_usuario',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tutor',
            name='codigo_como_firma',
            field=models.CharField(default='NW4RC', max_length=5, unique=True, verbose_name='Firma'),
        ),
    ]
